<?php

/**
 * @file
 * Module file for tableau_accessibility_block.
 */

/**
 * Implements hook_block_theme().
 */
function tableau_accessibility_block_theme($existing, $type, $theme, $path) {
  return [
    'tableau_accessibility_block__content' => [
      // In case we need to pass data to the twig template.
      'variables' => [
        'button_text' => 'Analyze Accessibility',
      ],
    ],
  ];
}
